## Expected Accuracy

In [4]:
import os
import json
import pandas as pd

def get_acc(dataset_name: str, model_name: str) -> float:
    filepath = f"../outputs/{dataset_name}__{model_name}/ground_truth_summary.json"
    if not os.path.exists(filepath):
        return None
    with open(filepath, "r") as f:
        data = json.load(f)
    return data["mean_accuracy"]

dataset_names = ["triviaqa-validation", "simpleqa-verified", "gsm8k-test", "math-500", "aime25-test", "mmlu-validation", "gpqa-diamond"]
model_names = ["Olmo-3-7B-Instruct", "Qwen3-8B-non-thinking", "gpt-oss-20b"]

import pandas as pd

# Construct a DataFrame with model_names as rows, dataset_names as columns, and values are accs
acc_matrix = []
for model in model_names:
    row = []
    for dataset in dataset_names:
        acc = get_acc(dataset, model)
        row.append(acc)
    acc_matrix.append(row)

df = pd.DataFrame(acc_matrix, index=model_names, columns=dataset_names)
df

,triviaqa-validation,simpleqa-verified,gsm8k-test,math-500,aime25-test,mmlu-validation,gpqa-diamond
Olmo-3-7B-Instruct,0.488363,0.033590,0.933131,0.90056,0.411333,0.704572,0.436414
Qwen3-8B-non-thinking,0.603952,0.052145,0.935641,0.82964,0.203667,0.793965,0.496465
gpt-oss-20b,0.650733,0.060100,0.957566,0.95662,0.739113,0.893788,NaN

# Few-Shot Verbalized Confidence

In [1]:
import os
import json
import pandas as pd

In [3]:
def get_metrics(dataset_name: str, model_name: str, method_name: str) -> float:
    filepath = f"../estimator_results/few_shot_verbalized_confidence/{dataset_name}__{model_name}/evaluation_metrics.json"
    if not os.path.exists(filepath):
        return None
    with open(filepath, "r") as f:
        data = json.load(f)
    return data[method_name]

dataset_names = ["triviaqa-validation", "simpleqa-verified", "gsm8k-test", "math-500", "aime25-test", "mmlu-validation", "gpqa-diamond"]
model_names = ["Qwen3-8B-non-thinking", "gpt-oss-20b"]

# Construct a DataFrame with model_names as rows, dataset_names as columns, and values are accs
acc_matrix = []
for model in model_names:
    row = []
    for dataset in dataset_names:
        acc = get_metrics(dataset, model, 'mse')
        row.append(acc)
    acc_matrix.append(row)

df = pd.DataFrame(acc_matrix, index=model_names, columns=dataset_names)
df

,triviaqa-validation,simpleqa-verified,gsm8k-test,math-500,aime25-test,mmlu-validation,gpqa-diamond
Qwen3-8B-non-thinking,0.272362,0.369377,0.042908,0.072851,0.335717,0.134302,0.255437
gpt-oss-20b,0.121695,0.158285,0.023736,0.019978,0.058362,0.055597,0.103405