## Expected Accuracy

In [1]:
import os
import json
import pandas as pd

def get_acc(dataset_name: str, model_name: str) -> float:
    filepath = f"../outputs/{dataset_name}__{model_name}/ground_truth_summary.json"
    if not os.path.exists(filepath):
        return None
    with open(filepath, "r") as f:
        data = json.load(f)
    return data["mean_accuracy"]

dataset_names = ["triviaqa-validation", "simpleqa-verified", "gsm8k-test", "math-500", "aime25-test", "mmlu-validation", "gpqa-diamond"]
model_names = ["Olmo-3-7B-Instruct", "Qwen3-1_7B-non-thinking", "Qwen3-4B-non-thinking", "Qwen3-8B-non-thinking", "Qwen3-14B-non-thinking", "gpt-oss-20b"]

import pandas as pd

# Construct a DataFrame with model_names as rows, dataset_names as columns, and values are accs
acc_matrix = []
for model in model_names:
    row = []
    for dataset in dataset_names:
        acc = get_acc(dataset, model)
        row.append(acc)
    acc_matrix.append(row)

df = pd.DataFrame(acc_matrix, index=model_names, columns=dataset_names)
df

,triviaqa-validation,simpleqa-verified,gsm8k-test,math-500,aime25-test,mmlu-validation,gpqa-diamond
Olmo-3-7B-Instruct,0.488363,0.033590,0.933131,0.90056,0.411333,0.704572,0.436414
Qwen3-1_7B-non-thinking,0.269639,0.030800,0.817968,0.71370,0.102000,0.632051,0.314596
Qwen3-4B-non-thinking,0.478810,0.041040,0.919083,0.82882,0.210000,0.756395,0.437525
Qwen3-8B-non-thinking,0.603952,0.052145,0.935641,0.82964,0.203667,0.793965,0.496465
Qwen3-14B-non-thinking,0.683141,0.063030,0.952843,0.86426,0.256333,0.825278,0.534394
gpt-oss-20b,0.650733,0.060100,0.957566,0.95662,0.739113,0.893788,0.669726

## P(True) or Verbalized Confidence

In [11]:
import json

metric = "spearman_r"
method = "verbalized_confidence"  # "verbalized_confidence" or "ptrue"
isotonic = True
MODEL2GPU = {
    "Olmo-3-7B-Instruct": "RTXPro6000",
    "Qwen3-8B-non-thinking": "RTXPro6000",
    "gpt-oss-20b": "A40",
}
def get_metric(
    model_name: str,
    dataset_name: str,
    metric: str,
    isotonic: bool = False,
) -> float:
    filepath = f"../estimator_results/{method}/{dataset_name}__{model_name}/evaluation_metrics_cc.json"
    if isotonic:
        filepath = filepath.replace("cc.json", "cc_isotonic.json")
    with open(filepath, "r") as f:
        data = json.load(f)
    return data[metric]

model_names = ["Olmo-3-7B-Instruct", "Qwen3-8B-non-thinking", "gpt-oss-20b"]  #
dataset_names = ["triviaqa-validation", "simpleqa-verified", "gsm8k-test", "math-500", "aime-test", "mmlu-test", "gpqa-diamond"]
# dataset_names = ["triviaqa-train", "simpleqa-train", "gsm8k-train", "math-train", "aime-train", "mmlu-validation", "gpqa-train"]

import pandas as pd

matrix = []
for model in model_names:
    row = []
    for dataset in dataset_names:
        metric_value = get_metric(model, dataset, metric, isotonic)
        row.append(metric_value)
    matrix.append(row)

df = pd.DataFrame(matrix, index=model_names, columns=dataset_names)
df

,triviaqa-validation,simpleqa-verified,gsm8k-test,math-500,aime-test,mmlu-test,gpqa-diamond
Olmo-3-7B-Instruct,0.344297,0.092836,0.132510,0.157583,0.359274,0.169595,0.169404
Qwen3-8B-non-thinking,0.319215,0.035169,0.063590,0.189057,0.168217,0.306875,0.081122
gpt-oss-20b,0.668011,0.325404,0.250595,0.355791,0.725440,0.507468,0.591203